kind: pipeline
type: docker
name: default

environment:
  HTTP_PROXY: http://git.lcpu.dev:7890
  HTTPS_PROXY: http://git.lcpu.dev:7890
  ALL_PROXY: http://git.lcpu.dev:7890

steps:
  - name: test
    image: loongcr.lcpu.dev/lcpu/archlinux:base-devel
    commands:
    - cd gcc
    - pacman -Sy && pacman -S --noconfirm --needed fakeroot devtools
    - echo 'MAKEFLAGS="-j64"' | sudo tee -a /etc/makepkg.conf
    - useradd builduser -m
    - chown -R builduser /drone/src/
    - su builduser bash
    - core-testing-loong64-build -- --nocheck
node:
  size: user
