kind: pipeline
type: exec
name: default

platform:
  os: linux
  arch: loong64

steps:
  - name: test
    commands:
    - cd gcc
    - pacman -Sy && pacman -S --noconfirm --needed fakeroot devtools
    - core-testing-loong64-build -- --nocheck

node:
  type: user
