kind: pipeline
type: exec
name: default

steps:
  - name: test
    commands:
    - cd gcc
    - pacman -Sy && pacman -S --noconfirm --needed fakeroot devtools
    - core-testing-loong64-build -- --nocheck
